### ISSUE TITLE
Formatting and analysis codes

### ISSUE THREAD

**Issue by wbirru** [mkuiper/MD_workflow_py#14]
Hi Mike,

I have pulled the formatting of check_job output and the analysis script in the analysis folder.

Cheers,
Emanuel

**Comment by mkuiper** [comment]
Hi Emanuel!
I thought I'd go home and work on this paper. Needs to get done this week!
Catch you tomorrow.
Cheers,
Mike

**Comment by wbirru** [comment]
Ok Mike,

I am teting mdwf using different samples and it seems it is is working smoothly specially in handling when there is a problem in the simulation.

Enjoy your writing.

Cheers,
Emanuel
